/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FinancialSummary = IDL.Record({
  'totalIncome' : IDL.Int,
  'totalExpenses' : IDL.Int,
  'netBalance' : IDL.Int,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat32,
  'transactionType' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : Time,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Nat32],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat32], [], []),
  'editTransaction' : IDL.Func(
      [IDL.Nat32, IDL.Int, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat32], [Transaction], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FinancialSummary = IDL.Record({
    'totalIncome' : IDL.Int,
    'totalExpenses' : IDL.Int,
    'netBalance' : IDL.Int,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat32,
    'transactionType' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : Time,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Nat32],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat32], [], []),
    'editTransaction' : IDL.Func(
        [IDL.Nat32, IDL.Int, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat32], [Transaction], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };